### ISSUE TITLE
Still working？

### ISSUE THREAD

**Issue by linonetwo** [elantion/SyncOSS#1]
我在搭一个学校内网的校园 APP，打算东西存内网，fall back 到外网的 OSS，不过还没开 OSS，考察中，这个项目最近都没有维护了，是否还能正常用于生产环境？

**Comment by elantion** [comment]
由于目前没有在我自已的项目中使用，所以我没去测试还能不能正常使用。但我猜应该没有问题，你可以先试试，如果真不能使用，我会去修复。
日后我会开发一个基于该项目的软件，用于前端资源的同步，但由于公司作业比较多，所以不知道什么时候才会开始。。。

**Comment by linonetwo** [comment]
唉 都是公司忙……
