### ISSUE TITLE
你好，关于http头被指定的问题

### ISSUE THREAD

**Issue by huyinghuan888** [elantion/SyncOSS#2]
oss.js中代码`ContentEncoding: 'utf-8'`, 对http头做了指定，这样导致上传的js和css类文件ContentEncoding都设置为utf-8，oss在不指定的情况下，默认上传的css和js文件在浏览器读取的时候Content-Encoding设置内容为gzip，支持压缩的，有些较大文件压缩率达30%，非常有用，所以望改进。这个工具非常好用，这种单向同步设计也很安全，谢谢分享。

**Comment by elantion** [comment]
很感谢你提的问题，已经修改好了，但由于我没账号测试了，希望你能帮我测试看看。
另外，你有兴趣指管这个项目吗？我已经不想再用阿里云的业务了。
如果仍有问题，请重开此问题。
